### ISSUE TITLE
CIFAR10 model trained in Keras error using BasicIterativeMethod

### ISSUE THREAD

**Issue by rowedenny** [tensorflow/cleverhans#1016] opened 2019-03-25 20:18 UTC
**Describe the bug**
tensorflow.python.framework.errors_impl.InternalError: Invalid loop structure: Mismatched parent frames for "while/while_context": "while/while_context" vs "". The node giving this error: {{node while/gradients/while/model/batch_normalization/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad/Enter}}This is an internal bug, please file a bug report with instructions on how to reproduce the error.

I assume it is related to batch_norm, where the implementation is the same the following,
https://github.com/geifmany/cifar-vgg/blob/master/cifar10vgg.py 

And I use the KerasModelWrapper to wrap the Keras sequential model. 

P.S  I find cleverhans works to generate adversaries for FGSM, deepfool, but the same error occurs for both BasicIterativeMethod and JSMA

My tensorflow version is 1.11.0 and cleverhans version is 3.0.1

**Comment by npapernot** [comment] 2019-04-04 23:29
Duplicate of #874 

Unfortunately we have not had success with having the underlying TF bug fixed so far. This problem may disappear with TF2 though

**Closed by npapernot** 2019-04-04 23:29 UTC
