### ISSUE TITLE
InvalidArgumentError: Retval[0] does not have value 

### ISSUE THREAD

**Issue by chenhx1992** [tensorflow/cleverhans#456] opened 2018-07-14 14:10 UTC
Hi, 

When I use the BasicIterativeMethod, I encounter a problem:

bim = BasicIterativeMethod(wrap, sess=sess)
bim_params = {'eps': 0.2, 'eps_iter': 0.05, 'nb_iter': 10, 'ord': 2, 'y_target': None}
adv_x = bim.generate(x, **bim_params)

until here, the code worked well, 

Then I tried to use the following code to get adversarial example in numpy array, and some errors occur:

feed_dict = {x: X_test}
adv_sample = sess.run(adv_x, feed_dict)

Traceback (most recent call last):

  File "<ipython-input-36-e66cca37c6f5>", line 3, in <module>
    adv_sample = sess.run(adv_x, feed_dict)

  File "/Users/chenhx1992/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)

  File "/Users/chenhx1992/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)

  File "/Users/chenhx1992/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)

  File "/Users/chenhx1992/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: Retval[0] does not have value

This problem don't occur when I use FastGradientMethod. 

Is there anything I do wrong? 

Hope get your valuable suggestion. Thanks in advance!

**Comment by aashish-kumar** [comment] 2018-07-16 11:14
I tried this. It is working fine. We might need slightly more information to help. You can modify cleverhans_tutorial/mnist_tutorial_tf.py to figure out what you might be doing wrong.

**Comment by goodfeli** [comment] 2018-07-16 19:04
For now I'll close this because Aashish could not reproduce. Feel-free to re-open if you have a short script we can just download and run to reproduce.

**Closed by goodfeli** 2018-07-16 19:04 UTC
