### ISSUE TITLE
Can't pickle the model from the CIFAR10 tutorial

### ISSUE THREAD

**Issue by davidglavas** [tensorflow/cleverhans#928] opened 2018-12-15 20:14 UTC
How to store the CIFAR10 model from the [tutorial](https://github.com/tensorflow/cleverhans/blob/a9f4425867d981ac732a23dce60eb7d08c24ebca/cleverhans_tutorials/cifar10_tutorial_tf.py)? I tried doing the same as in the MNIST tutorial by writing the following after the model has been trained ([line 136](https://github.com/tensorflow/cleverhans/blob/a9f4425867d981ac732a23dce60eb7d08c24ebca/cleverhans_tutorials/cifar10_tutorial_tf.py#L136)):
```
with sess.as_default():
    save("cleanCIFAR10Model.joblib", model)
```

The model trains succesfully but while trying to store it with the above code the following exception occurs: `TypeError: can't pickle _thread.RLock objects`.

The model from the MNIST tutorial is stored in exactly the same way (pasting the above code after the training code). The only notable difference between the MNIST and CIFAR tutorials is the preprocessing at [lines 84 - 86](https://github.com/tensorflow/cleverhans/blob/a9f4425867d981ac732a23dce60eb7d08c24ebca/cleverhans_tutorials/cifar10_tutorial_tf.py#L84). I suspect the exception is caused by the [lambda](https://stackoverflow.com/questions/47066635/checkpointing-keras-model-typeerror-cant-pickle-thread-lock-objects) at lines 85-86 (since `x` and `y` are `tf.float32`'s and Keras does not support serializing tf.Tensor)?

Any suggestions for how to store the CIFAR model from this tutorial?

**Comment by goodfeli** [comment] 2018-12-17 16:55
The problem is that the model class itself does not support pickling.
TensorFlow Variables can't be pickled, so Models must be designed to avoid
returning any Variables in their __getstate__. It isn't anything to do with
the tutorial code.
I made an issue to track this:
https://github.com/tensorflow/cleverhans/issues/930

**Comment by goodfeli** [comment] 2018-12-19 17:39
Closing this issue because #930 says how to fix it

**Closed by goodfeli** 2018-12-19 17:39 UTC
