### ISSUE TITLE
TensorFlow issues weird error message

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/cleverhans#17] opened 2016-09-19 10:29 UTC
This seems harmless, but it is annoying. Not sure if we can fix it, since it may be a bug in TensorFlow itself.

At the end of the MNIST tutorial, I get this error message:
    Exception AttributeError: AttributeError("'NoneType' object has no attribute 'raise_exception_on_not_ok_status'",) in <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7fb09c05ad50>> ignored

**Comment by npapernot** [comment] 2016-11-19 20:47
@goodfeli I haven't seen this message in a while, do you agree to close this issue?

**Comment by goodfeli** [comment] 2016-11-19 20:56
I still get it consistently:
`Completed model training.
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f99aa445c88>>
Traceback (most recent call last):
  File "/opt/anaconda/4.2.0/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 522, in __del__
  File "/opt/anaconda/4.2.0/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 518, in close
  File "/opt/anaconda/4.2.0/lib/python3.5/contextlib.py", line 133, in helper
TypeError: 'NoneType' object is not callable`

**Comment by goodfeli** [comment] 2017-01-20 20:19
Looks fixed now, maybe by updating tensorflow to 0.12

**Comment by goodfeli** [comment] 2017-01-20 22:52
It still happens, it is just flaky.

Out of three runs, I had this happen once:
    Completed model training.
    Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f5564ed4f28>>
    Traceback (most recent call last):
      File "/home/ian/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
    UnboundLocalError: local variable 'status' referenced before assignment

**Comment by dguera** [comment] 2017-03-07 17:39
I get the following message which is somehow related:

Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f4e28be0668>>
Traceback (most recent call last):
  File "/data/dgueraco/tensorflow/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 582, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'

Adding a simple `del sess` at the end of the tutorial fixes it.

**Comment by goodfeli** [comment] 2017-03-27 22:04
I don't get this error message anymore. Can re-open if someone else does.

**Comment by gautam1858** [comment] 2017-09-08 05:14
I am getting this error `AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'` when I run keras code

**Comment by goodfeli** [comment] 2017-09-08 14:01
Thanks for the report. Re-opening the issue.

**Comment by brennn-rpi** [comment] 2017-09-08 17:30
I am also periodically getting a similar error at the end of my program when using Keras
`Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7fc0665ff2b0>>
Traceback (most recent call last):
  File ".../lib/python3.4/site-packages/tensorflow/python/client/session.py", line 595, in __del__
TypeError: 'NoneType' object is not callable`
I'm using Keras version 2.0.5 and Tensorflow version 1.2.1

**Comment by zyavrik** [comment] 2017-09-14 05:38
I can see the issue in Tensorflow 1.4dev.

**Comment by AngusG** [comment] 2017-09-20 12:57
A recent Travis build for #266 -- Python 2.7/TensorFlow 1.1.0 turns up a similar error:

`Exception AttributeError: "'NoneType' object has no attribute 'TF_NewStatus'" in <bound method` `Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f95ad07c610>> ignored`

It looks like the issue is well known here: https://github.com/tensorflow/tensorflow/issues/8652

**Comment by npapernot** [comment] 2017-09-20 16:19
The issue on the tensorflow tracker seems to imply that the problem only occurs when users imported Keras.

**Comment by npapernot** [comment] 2017-09-20 16:20
It appears that there is a fix but it has not been merged into TF yet.

**Comment by jackalhan** [comment] 2017-10-19 17:05
I am also getting this error while trying to save my weights. 

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f711d56b7b8>>
Traceback (most recent call last):
  File "~/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 701, in __del__
TypeError: 'NoneType' object is not callable

**Comment by jackalhan** [comment] 2017-10-19 17:13
And the issue happened in the following session.py block 

def __del__(self):
    # cleanly ignore all exceptions
    try:
      self.close()
    except Exception:  # pylint: disable=broad-except
      pass
    if self._session is not None:
      # We create `status` outside the `try` block because at shutdown
      # `tf_session` may have been garbage collected, and the creation of a
      # status object may fail. In that case, we prefer to ignore the failure
      # and silently leak the session object, since the program is about to
      # terminate.
      status = None
      try:
        **status = tf_session.TF_NewStatus()**
        if self._created_with_new_api:
          tf_session.TF_DeleteSession(self._session, status)
        else:
          tf_session.TF_DeleteDeprecatedSession(self._session, status)
      except AttributeError:
        # 'NoneType' object has no attribute 'TF_NewStatus'
        pass
      finally:
        if status is not None:
          tf_session.TF_DeleteStatus(status)
      self._session = None

**Comment by meldron** [comment] 2017-11-30 14:20
I have got the some problem with Tensorflow + Keras.

Tensorflow: 1.3.0
Keras: 2.0.6

```^CTraceback (most recent call last):
  File "main.py", line 172, in <module>
    main()
  File "main.py", line 142, in junk_sort
    p = model.predict(i)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 909, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1517, in predict
    batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1141, in _predict_loop
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2268, in __call__
    **self.session_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
```

**Comment by anasvaf** [comment] 2017-12-04 13:57
I am still getting the same error with Tf: 1.4.0 and Keras 2.1.2

**Comment by mvrozanti** [comment] 2017-12-09 11:56
TF 1.4.0 and Keras 2.0.8

**Comment by goodfeli** [comment] 2017-12-12 17:12
It doesn't seem to have negative consequences besides an annoying amount of text.

We don't need more reports that it's happening here in the CleverHans repository.

Feel free to comment on the open issue for TensorFlow: https://github.com/tensorflow/tensorflow/issues/8652

All we can do in CleverHans is wait for the source of the issue to be fixed.

**Comment by anasvaf** [comment] 2017-12-12 17:19
@goodfeli thanks for the response!
The only annoying issue is that I am trying to save the classification results in a csv file for some audio clips and it doesn't reach that line. However, I get the results in the terminal.
I figured I have to restart Atom in my case and open a new terminal to re-run the code correctly

**Comment by goodfeli** [comment] 2017-12-12 17:28
If you're having trouble with code not executing, open a new issue. This issue is just to track the weird error message, which seems to originate external to CleverHans.

**Comment by butterl** [comment] 2018-02-03 07:48
get same kind of error with：

tensorflow:1.5.0
keras:2.1.3

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f191b5f8860>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable

```

**Comment by Federico-Dignazio** [comment] 2018-02-13 15:12
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f5b4bcab9e8>>
Traceback (most recent call last):
  File "/home/rps/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable


Same error here.
This happens to me ONLY when I run a script while the same script is already running.


Keras: 2.1.2
Tensorflow: 1.4.1

**Comment by ValdezBalderas** [comment] 2018-03-08 15:09
I get the error once every three runs or so, Tensorflow 1.5, Linux. This is the code:
```
a = tf.get_variable('a', initializer=[23.6])
with tf.get_default_graph().gradient_override_map({"Round": "Identity"}):
    x = tf.round(a)

g = tf.gradients(x, a)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    G = sess.run(g)
    print(G)
```
Sometimes error:
```
[array([1.], dtype=float32)]
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f873c429828>>
Traceback (most recent call last):
  File "/user/dlb/virt_env_tf15_cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 702, in __del__
TypeError: 'NoneType' object is not callable

```

**Comment by goodfeli** [comment] 2018-03-09 17:07
Since we know that this originates external to CleverHans, there is no need to submit further reports of it here. Follow the issue on the TensorFlow repository.

**Comment by jmgilmer** [comment] 2018-03-15 17:23
@goodfeli shall we close this issue then?

**Comment by nottombrown** [comment] 2018-04-12 23:42
Closing this issue because it is outside the domain of CleverHans.

Here's the link to the open issue in Tensorflow:
https://github.com/tensorflow/tensorflow/issues/8652

**Closed by nottombrown** 2018-04-12 23:42 UTC
Labels: waiting for tensorflow

**Comment by iperov** [comment] 2018-11-28 18:32
```
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow
.python.client.session.BaseSession._Callable object at 0x0000000023596048>>
Traceback (most recent call last):
  File "F:\DeepFaceLab\_internal\bin\lib\site-packages\tensorflow\python\client\
session.py", line 1413, in __del__
AttributeError: 'NoneType' object has no attribute 'raise_exception_on_not_ok_st
atus'
```

same error. TF 1.11.0 , keras 2.2.4

**Comment by iperov** [comment] 2019-02-28 06:31
still not solved

**Comment by npapernot** [comment] 2019-02-28 17:39
I think it would be best to raise an issue on the tensorflow tracker or to ping the existing issue: https://github.com/tensorflow/tensorflow/issues/8652

**Comment by iperov** [comment] 2019-02-28 17:49
my last tests show that is keras issue 
https://github.com/keras-team/keras/issues/11751

**Comment by waterwheel31** [comment] 2020-03-15 07:16
I have the same issue. Keras occasionally fails after finishing trainings.
